server:
  port: 8778

spring:
  application:
    name: spring-cloud-zuul

eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:3333/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: spring-cloud-ribbon
    api-b:
      path: /api-b/**
      serviceId: spring-cloud-feign