server:
  port: 3001

spring:
  application:
    name: spring-cloud-demoA

#注册中心指向start    
eureka:
  #instance:
   # instance-id: spring-cloud-demoA
    #appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:3333/eureka/
#注册中心指向end
