server:
  port: 8777

spring:
  application:
    name: spring-cloud-feign

eureka:
  instance:
    instance-id: spring-cloud-feign
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:3333/eureka/

feign:
  hystrix:
    enabled: true
